- name: JFFI install and other dependancies
  apt: 
        name: [ 'libjffi-jni', 'libjffi-java', 'default-jre' ] 
        state: present 
        update_cache: true

- name: Get deb file from elastic.co
  get_url:
        url: "{{ item }}"
        dest: /tmp/
  with_items:
        - https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}.deb
        - https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}.deb.sha512

- name: Validate checksum
  command: chdir=/tmp shasum -a 512 -c "/tmp/logstash-{{ logstash_version }}.deb.sha512"

- name: Install Logstash
  apt:
        deb: "/tmp/logstash-{{ logstash_version }}.deb"
        state: present
